"""add role and token limits to users

Revision ID: e1b0ec237ab8
Revises: 063b2e3f80bb
Create Date: 2026-09-12 10:10:37.200596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b0ec237ab8'
down_revision: Union[str, Sequence[str], None] = '063b2e3f80bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.add_column('users', sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('token_limit', sa.Integer(), server_default='50000', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_limit')
    op.drop_column('users', 'tokens_used')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
